### ISSUE TITLE
LAB_AK_05_Lab5_Ex2_Safe_Links.md/Task 2/Step 18

### ISSUE THREAD

**Issue by AnthonyOakley** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#44]
# Module:  05
##### Step: 18

Description of issue
Never got warning message.  Checked several days with same result.

**Comment by MordyNYC** [comment]
No

**Comment by tfrink** [comment]
I was unable to reproduce this issue. When I clicked on the link in the email to the tailspin toys site, it returned the site showing "This website is classified as malicious". I have attached a screenshot of the site that was returned during my testing. 

Question - after completing task 1, did you wait 30 minutes before performing task 2, as the instructions said to do?

![malicious web site](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/12913870/cc9e6fb2-0be5-452a-a739-51df72a75fe0)
