### ISSUE TITLE
LAB_AK_09_Lab9_Ex1_Implement Sensitivity labels.md/Task 4/Step 19

### ISSUE THREAD

**Issue by AnthonyOakley** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#48]
# Module:  09
##### Step: 19

Description of issue
Could not download Word document and therefore could not finish Lab 9.

**Comment by Nimra-Maryam** [comment]
Any Update on this issue?

**Comment by maquinl** [comment]
@Nimra-Maryam We are looking into this and reply back once a solution is found, thanks!

**Comment by tfrink** [comment]
I was unable to reproduce this problem. I was able to download the document multiple times during lab testing. We will keep an eye on this situation in case it occurs in later testing.
