### ISSUE TITLE
How can I run this lab? newbie question

### ISSUE THREAD

**Issue by GustavoAlmeidaAboud** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#5]
Hello,

I created the m365 Dev account with 90Days trial, but how can I run the rest of the lab? Some exercices require VMS with Active Directory and such.

Thank you and kind regards,
Gustavo

**Comment by tfrink** [comment]
The labs require that you use a lab-hosted VM version that uses an M365 trial tenant that's preloaded with a set group of predefined users. The labs do not work in a bring your own subscription environment. You must use a tenant provided by an authorized lab hosting provider (ALH).
