### ISSUE TITLE
LAB_AK_02_Lab2_Ex1_Manage_Admin_Delegation.md/Task 03/Step 26

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#50]
# Lab/Demo: 02
#### Step: 26

No error occurs when we input the password "Pa55w.rd."

![image](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/133017642/9749588e-d40d-4ece-8a80-92ec4a686ccf)

**Comment by tfrink** [comment]
Thank you for bringing this to our attention. We left out one part, which is that you only get the error when you also select the "Require this user to change their password when they first sign in" check box. So we re-wrote this step as follows:

Verify the **Require this user to change their password when they first sign in** checkbox is selected (if not, then select it now to show a checkmark). Enter **Pa55w.rd** in the **Password** field. Note that the **Password** field indicates this is a Strong password. <br/>

	However, now select the **Require this user to change their password when they first sign in** checkbox to clear it. Note the error message that appears indicating the password (Pa55w.rd) contains a word, phrase, or series of numbers that makes it easily guessable. In this case, you entered a variation of the word **password**, which will trigger this error. The system allows you enter this password if you force the user to change it at their first sign-in. But if you don't force the user to enter a different password at their first sign-in, then this password isn't allowed.
