### ISSUE TITLE
LAB_AK_03_Lab3_Ex2_Implement_Identity_Synch.md/Task 1/Step 9

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#51]
# Lab/Demo: 03
#### Step: 09

In the list of requirements presented in step 9, the option 1 requirement needs to be eliminated which states "I have a single or multiple connected forests that I need to sync users and groups from." since it is not available within the user interface (UI).

![image](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/133017642/3d3b0133-c7de-4621-861a-e2605e07c5b5)

**Comment by tfrink** [comment]
Thank you for bringing this change to our attention. We removed the step to select the "I have a single or multiple connected forests that I need to sync users and groups from." checkbox.
