### ISSUE TITLE
Issue regarding the Microsoft Defender Alerts Notification in Lab 6 Exercise 2, 3 and 4

### ISSUE THREAD

**Issue by akn9050** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#56]
Description of issue:
There is an Issue regarding the Microsoft Defender Alerts Notification in Lab 6 Exercise 2, 3 and 4, alert emails are not getting received/triggered even after creating the policy alerts.

Repro steps:
https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/blob/master/Instructions/Labs/LAB_AK_06_Lab6_Ex2_Mailbox_Permission_Alert.md#task-2--validate-the-mailbox-permission-alert

https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/blob/master/Instructions/Labs/LAB_AK_06_Lab6_Ex3_SharePoint_Permission_Alert.md#task-2--validate-the--sharepoint-permissions-alert

https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/blob/master/Instructions/Labs/LAB_AK_06_Lab6_Ex4_eDiscovery_Alert.md#task-2--validate-the-default-ediscovery-alert

**Comment by Divyasri199** [comment]
Hello @tfrink , can you please have a look at the issue we have raised and suggest us with the workaround.

**Comment by tfrink** [comment]
Looking into it now. Thanks!

**Comment by tfrink** [comment]
In Lab 1, Exercise 1, one of the tasks is to turn on audit logging, which enables the alert notification system. You do so by selecting the banner that appears on the Audit page in Microsoft 365 Defender. Once you select the banner and it disappears, then audit logging is turned on. However, we're starting to see sporadic instances of where the banner doesn't disappear, and as a result, audit logging isn't turned on. We're not sure if this is a VM issue or a product issue. In either case, we are updating the lab instructions to provide a PowerShell command to turn on audit logging.
