### ISSUE TITLE
Group creation instructions need to be updated

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#59]
# Module: 01
#### Step: 3, 4

Description of issue
The instructions to create a Microsoft 365 group are out of date.

**Comment by tfrink** [comment]
Thanks Annette! I'll look into this and make the necessary updates.

**Comment by tfrink** [comment]
I made the necessary updates. I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
