### ISSUE TITLE
Add member to role group instructions need updating

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#60]
# Module: 6
#### Step: 6 onwards

The instructions to add Lynne to the role group aren't correct now and need to be updated.

**Comment by tfrink** [comment]
Thanks Annette! I'll look into this and make the necessary updates.

**Comment by tfrink** [comment]
I updated the instructions in this task to reflect the latest UI changes.

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
