### ISSUE TITLE
Lab 6, Ex 6 Instruction needs updating

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#61]
# Module: 6
#### Step: 7

You need to click on the "Tenant payloads" tab to see the "+Create a payload" link.

**Comment by tfrink** [comment]
Thanks Annette! I'll look into this and make the necessary updates.

**Comment by tfrink** [comment]
I updated the instructions as you mentioned. 

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
