### ISSUE TITLE
Changes to order of tasks in Lab 6

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#63]
# Module: 6
## Lab/Demo: 6

In exercises 2, 3 and 4, alert policies are set up and tested.  In each case, after the relevant action has been performed to trigger the alert, it can take up to 15 minutes before the alert email is received.

Why not rearrange the tasks so that all three alert policies are set up first and the alerts triggered, and then a final task gets the students to check that the alert emails have been received.

And in exercises 5 and 6, attack simulations are set up and tested.  Again, it can take 10 to 15 minutes before the phishing emails are is received.  Why not set up both simulations first, and then check that the two phishing emails have been received?

Occasional periods of waiting for things to happen in a lab is OK, but in this lab there are 5 such waits.  Of course, the trainer can tell the students to move on the next exercise while they're waiting for the previous email to arrive, but for some students this is too complicated and they get lost in the instructions.  (It sounds simple, but for less confident students it isn't.)

**Comment by tfrink** [comment]
Thank you Annette for the suggestions. It appears there have been product changes recently that are affecting the automatic email notifications. Your suggestions are an excellent resolution to this. I'll look to reorder the lab instructions ASAP. Thanks again!

**Comment by AnnetteGill** [comment]
Thank you, that will be very helpful!

**Comment by tfrink** [comment]
I created a new Lab 6, Exercise 7 that contains all the validation tasks from Exercises 2-6. Hopefully by the time you get to Ex 7, the emails from Ex 2-5 will be generated, and by the time you finish the validation tasks for Ex 2-5, the email for Ex 6 will be generated as well and ready to be validated.

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.

**Comment by AnnetteGill** [comment]
Thank you, that will be really helpful.
