### ISSUE TITLE
Lab 7, Ex 1, instructions for creating a group are wrong

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#64]
# Module: 7
### Task: 1

The instructions for creating the Compliance Test Users group need to be updated - the UI for creating groups has changed.

**Comment by tfrink** [comment]
Thanks Annette! I'll look into this and make the necessary updates.

**Comment by tfrink** [comment]
I updated the steps to create a mail-enabled security group in Task 1.

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
