### ISSUE TITLE
Lab 7, Ex 2, Retention policy wizard has changed

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#65]
# Module: 7
### Task: 2 and 3

In Task 2, after step 5, insert a step for the new "Policy Scope" page in the "Create retention policy" wizard.  (It's about choosing an Admin Unit.)

In Task 3, after step 5, insert a step for the new "Policy Scope" page in the "Create retention policy" wizard.

**Comment by tfrink** [comment]
Thanks Annette! I'll look into this and make the necessary updates.

**Comment by tfrink** [comment]
I updated the tasks to include the Policy Scope page when performing the wizard.

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
