### ISSUE TITLE
Lab 9, wizard to publish sensitivity label policy has changed

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#67]
# Module: 00
## Lab/Demo: 9
##Exercise: 1
#### Step: 36 and 37.  Also steps 42 and 43

When publishing a label, the options on the "Publish to users and groups" page have changed - there's no option to "Choose user or group".  

Clicking on Edit instead (at the right hand side) opens a page whose options don't match the instructions.

Steps 36 and 37 need to be updated.

Also, steps 42 and 43 are in the wrong order.  The "Default settings for meetings and calendar events" page comes before the "Default settings for Power BI content" page.

**Comment by tfrink** [comment]
Thanks Annette! I'll look into this and make the necessary updates.

**Comment by AnnetteGill** [comment]
Thanks Tony, for dealing with all of these issues!

**Comment by tfrink** [comment]
I updated these steps per the issues that Annette addressed. 

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
