### ISSUE TITLE
Tenants blocked from sending email (due to spam)

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#68]
All labs involved in sending emails.. (quite a few)

All tenants in the class this week (10+) are blocked from sending emails due to the IP addresses of the exchange online servers being marked by Microsoft as responsible for spam...

Not sure what can be done in such a short space of time but it effectively kills the lab experience for all students..

Appreciate they can be run after the course when it is released but... 

Ed

**Comment by tfrink** [comment]
Wow - let me take a look into this. I can say that I've been testing and fixing labs over the last two days, and yesterday I reviewed and updated all the alert and attack simulation exercises in Lab 6, and all 6 or 7 email notifications were sent without any issues. Let me check with the IT guys to see what I can find out.

**Comment by edbakermct** [comment]
Thanks

I tested it with OME (Purview) tasks today to demonstrate the portal and had to use one of my tenants not the lab tenant

**Comment by edbakermct** [comment]
Here you go Tony - the ndr report if that helps the folks at MS

Diagnostic information for administrators:

Generating server: SA1PR20MB4491.namprd20.prod.outlook.com

ed_baker@hotmail.com
Remote server returned '550 5.7.501 Service unavailable. Spam abuse detected from IP range. For more information please go to http://go.microsoft.com/fwlink/?LinkId=526653. S(2017052602) [BLAPR20MB3922.namprd20.prod.outlook.com 2023-12-14T14:47:42.385Z 08DBFC551B25948C]'

Original message headers:

Received: from SA1PR20MB4491.namprd20.prod.outlook.com
 ([fe80::ec76:8215:2a6:5554]) by SA1PR20MB4491.namprd20.prod.outlook.com
 ([fe80::ec76:8215:2a6:5554%7]) with mapi id 15.20.7091.028; Thu, 14 Dec 2023
 14:47:42 +0000
MIME-Version: 1.0
Content-Type: text/plain
Date: Thu, 14 Dec 2023 14:47:42 +0000
Message-ID:
	<SA1PR20MB4491C392EED5D10291859DC69A8CA@SA1PR20MB4491.namprd20.prod.outlook.com>
Subject: encrypt test

**Comment by edbakermct** [comment]
Discovered the issue - its the ALH VM ip range that has been blacklisted... 

go deploy - not sure how to get round that other than by running all email sends from an in private browser outside the vm. - i will notify go deploy

**Comment by edbakermct** [comment]
I have updated the github issues - its godeploy ips, they have given a work around...

We used ourt own clients to send emauils but you can send a message to MS and ge tit released by confirming your domain.

**Comment by tfrink** [comment]
Thanks Ed for the update. Based on your final message, it sounds like godeploy resolved this issue. I just want to verify whether that's correct before I close this issue. Or is there anything else you still need from me?

**Comment by edbakermct** [comment]
Not resolved - but a workaround they don’t fix it for you - they expect each user to send an email to ms to get it cleared for that IP, less than ideal but it is what it is - please do close it

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
