### ISSUE TITLE
MS-102T00 | All Labs. Lab 3 Ex2, Under Task 5 and Point 9.

### ISSUE THREAD

**Issue by yasirqazi** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#70]
# Module: MS102T00
#### Step: 9

Description of issue
The scope is set to current user when we are installing only Group and User module for Microsoft Graph. The issue arises when we we are importing the group and user module. The resolution i found out was that if one installs complete Microsoft Graph instead of Modules without user scope so it fixes the issue.

**Comment by maquinl** [comment]
Hi @yasirqazi - We have tested this issue and do not reproduce the same behavior when installing the modules for Microsoft.Graph.Users & Microsoft.Graph.Groups in an elevated powershell instance. Importing the modules produces no errors, and we can proceed with the rest of the steps in the task.

If you are seeing a specific error when importing the module, please re-open this issue and attach a screenshot. Thank you!
