### ISSUE TITLE
Lab 1, Ex 2: deleting a Microsoft 365 group

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#71]
# Module: 01
## Lab/Demo: 01
##Exercise: 2
#### Step: 32 and 33

In step 32, if you select the ellipsis, it actually says "Delete team", not "Delete group".

In step 33, the button actually says "Delete Team", not "Delete group"

This is because we have created Inside Sales as a group with a team.

**Comment by maquinl** [comment]
@AnnetteGill Thank you for the feedback. We have updated the terms from "group" to "team" in the steps above.
