### ISSUE TITLE
Lab 6, Ex 5: Payload is missing

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#72]
# Module: 6
#### Step: 9

This step asks you to choose the "2 Failed messages" payload.  There's no payload with this name in the list of payloads being shown.

**Comment by maquinl** [comment]
@AnnetteGill thanks for the feedback, we have updated the instructions to reflect a new different payload and the option to select any other payload should that option no longer exist in the future. In the context of this specific exercise, it doesn't matter which payload is selected.

**Comment by AnnetteGill** [comment]
Thank you, that's good.
