### ISSUE TITLE
Lab 8, Ex  1, Task 1: confusing text

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#76]
# Module: 8
#### Step: 7

The text in this step is confusing. You've made all the text from _-Name_ to _...from being sent.**_ copiable.

Skillable Labs have interpreted this as meaning that all of that text must be copied into the Name and the Description fields, which is wrong.  They say they've done that because of the way you've written this step.

GoDeploy Labs have done it correctly.

Please see screenshots below of this step in GoDeploy's lab and in Skillable's lab.

Please could you modify step 7 so that it's clear what must be copied into the Name field and what must be copied into the Description field?

GoDeploy's step 7 instruction:

![GoDeploy Labs step 7](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/24852320/9a208cf1-95a5-467a-ab80-71d4b5f22564)

Skillable's step 7 instruction

![Skillable Labs step 7](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/24852320/db238548-b433-488b-8361-3a0d9630bf42)

**Comment by tfrink** [comment]
I fixed this to exclude the extra verbiage and just include the text to be entered.

**Comment by AnnetteGill** [comment]
Thanks very much for fixing this so quickly.
