### ISSUE TITLE
Lab 1, Ex 2, Task 3, Step 23

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#79]
# Module: 1
#### Step: 23

The instructions say to "enter the following information"  in the Name and the Description fields. 

For Description, it shouldn't include the words "and then select Next". Those words should be on the next line - they are part of the instructions. 

For Description, It should simply say "IT administrative personnel"

![Lab 1 Ex 2 Task 3 Step 23](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/24852320/04370e39-03a8-4f97-bcc2-eb28b844d4b3)

**Comment by tfrink** [comment]
Thanks Annette. I removed that text from the Description field and added it to the instruction on step 23, as follows:

23. On the **Set up the basics** page, enter the following information and then select **Next**:

**Comment by AnnetteGill** [comment]
Thank you!
