### ISSUE TITLE
Lab 2, Ex 1, Task 3

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#80]
# Module: 2
### Task: 3

Steps 41 and 47 both refer to blocking or unblocking a user account.  They say to do steps 33 to 36 to block/unblock the user.

But steps 33 to 36 are actually telling you how to reset a user's password, not how to block their sign-in.

**Comment by tfrink** [comment]
Thanks Annette! I have updated the step numbers to 37 through 40.
