### ISSUE TITLE
Lab 3, Ex 2, Task 5 - tabs in the Active Teams and groups page

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#81]
# Module: 3
## Lab/Demo: 3
##Exercise: 2
#### Step: 5

When checking if the Manufacturing group (which is a mail-enabled security group) has synced to Entra ID, this step says to look in the tab called "Mail-enabled security".

This tab doesn't exist now. The student should look in the "Security" tab.

**Comment by tfrink** [comment]
Thanks Annette! I have applied the changes.
