### ISSUE TITLE
Lab 4, Ex 1, finding PIM in Entra admin center

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#82]
# Module: 4
#### Step: 5

PIM is no longer listed under feature highlights on the home page of the Entra admin center.

The student needs to expand Identity Governance and then choose Privileged Identity Management.

**Comment by tfrink** [comment]
Thanks Annette! I've applied the changes.
