### ISSUE TITLE
Lab 9

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#83]
# Module: 9 
## Exercise: 1

Task 2, steps 10 and 11. The terminology in the wizard for creating a label that will encrypt an item has changed.

In step 10, the option "Apply or remove encryption" is now called "Control Access".
In step 11, the page is now called "Access control".

Task 4, step 12, the username for Joni is missing the final   .com

Task 4, step 18, we don't see the document in a tile in the body of the email.  We just see a link to the document in the email. So we can't select the down arrow in the tile to download the document.  We have to click on the link to open the document in Word and then download it from there.

**Comment by tfrink** [comment]
Thanks Annette! All updates are applied.
