### ISSUE TITLE
Fix the restore deleted group work-around in Lab 1, Ex 2, Task 4

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#85]
# Module: 01
#### Task: 04

Description of issue
A work-around was created due to the change in the Get-MgDirectoryDeletedItem, we could use the Get-MgDirectoryDeletedItemAsGroup to get the Id and go back to the old (simple) instructions.

Repro steps:
1. In Step 7, Run **MgDirectoryDeletedItemAsGroup** and copy the ID value for "Inside Sales".
1. In Step 8, Run **Restore-MgDirectoryDeletedItem -DirectoryObjectId** and paste the ID.
2.  (And remove the work-around note from the task description.)

**Comment by tfrink** [comment]
Thanks ITBlandMCT!!! We were planning to test this lab in the upcoming weeks to see if the PowerShell had been updated since our last test to see if it returned the object ID. Thank you for providing this solution. I have applied it to the lab steps.
