### ISSUE TITLE
Unable to save themes in Microsoft 365 Admin Center

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#87]
####  Step 22 - Save the custom theme:

Description of issue
Whenever attempting to save a custom theme in Microsoft 365 Admin Center, it always results in an error of "Sorry, we couldn't save your theme. Please try again later" [p1].

This has also been reproduced outside of the lab [p2], which leads me to believe it's a platform error on M365 Admin center itself.

[p1]

![Custom There Task 3](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/94069201/d294dac7-e2d2-46ef-ae5c-0e5078386998) 

[p2]

![image-1](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/94069201/403f6261-0a81-4359-b7fa-ab65fa6ccdfe)

**Comment by tfrink** [comment]
This is a known issue. Sometimes it works and other times it doesn't. I've added a note to this exercises. It's still a valuable exercise to provide experience on creating a custom theme, even if you can't save it
