### ISSUE TITLE
Learning Path 1 - Lab 1 - Exercise 2 - Task 4 - Step8

### ISSUE THREAD

**Issue by FeckeIT** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#88]
# Module: 01
#### Step: 08

Description of issue

the cmdlet "**Restore-MgDirectoryDeletedItem -DirectoryObjectId $DeletedGroup.id 'paste in the object ID for the Inside Sales group here'"** fails, because no Variable **$DeletedGroup** ist definded before. The cmdlet must change to "**Restore-MgDirectoryDeletedItem -DirectoryObjectId 'paste in the object ID for the Inside Sales group here'"** than it works

Repro steps:

1. Delete the Variable $DeletedGroup.ID
2. copy and paste the Group ID from Inside sales 
1.

Greets,
Wolfgang

**Comment by tfrink** [comment]
Thanks Wolfgang for bringing this oversight to our attention. I removed the variable.
