### ISSUE TITLE
Lab 6, Ex 7, Task 4

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#92]
# Module: 6
## Lab/Demo: 6
##Exercise: 7
#### Step: 3-4

The email the user receives might not have this subject and text. It depends what payload you selected when setting up the spear phishing simulation in Exercise 5.

**Comment by tfrink** [comment]
Thanks Annette. I have updated the steps accordingly. Please note that I'm releasing an update to MS-102 on 6/14. This includes a number of minor updates to the labs. This fix will be included in that release.

**Comment by AnnetteGill** [comment]
Thanks Tony.  Will the changes to MS-102 later this month be very extensive? I'm just trying to work out how much prep I'd need to do for the updated version.
