### ISSUE TITLE
Set up Adatum's Organization Profile Failed

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#99]
# Module: 01
#### Step: 17

When I trying to update the organization profile and then save it, but it's given me the error:
"**_Object reference not set to an instance of an object_**,". We also did try troubleshooting to resolve this, but we didn't resolve kindly let us know why we face this issue. Previously it's work fine.

**The screenshot has attached in it:**
![image](https://github.com/user-attachments/assets/6dde366f-37db-4f3b-83cc-b4d9992e09fd)

**Comment by LewisGoDeploy** [comment]
I was previously experiencing the same problem but appears to be working today.

**Comment by tfrink** [comment]
Unfortunately, this appears to be a hit or miss error that has been appearing lately in our tenant. We're unable to determine why this is happening. The fact that you can't save your org profile changes is not a show-stopper that affects anything later on. We will continue to troubleshoot it to see if we can resolve it, but for the moment, we've added a note to this step to indicate that if this error occurs, simply ignore it and continue on with the lab.
